# -*- coding: utf-8 -*-
"""Flower_identification_Tas1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18rY8cujvIczEZJkUiLk6Css18JzFxEyJ
"""

# ============================================================
# TASK 1: Iris Flower Classification using Machine Learning
# ============================================================

import os
import zipfile
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# -------------------------------
# STEP 1: Dataset paths
# -------------------------------
ZIP_PATH = "Flower_Dataset.zip"
EXTRACT_PATH = "flower_dataset"

# -------------------------------
# STEP 2: Extract dataset
# -------------------------------

if not os.path.exists(EXTRACT_PATH):
    with zipfile.ZipFile(ZIP_PATH, 'r') as zip_ref:
        zip_ref.extractall(EXTRACT_PATH)

print("Dataset extracted successfully.")

# -------------------------------
# STEP 3: Load CSV file
# -------------------------------

csv_file = None
for file in os.listdir(EXTRACT_PATH):
    if file.endswith(".csv"):
        csv_file = os.path.join(EXTRACT_PATH, file)
        break

if csv_file is None:
    raise FileNotFoundError("No CSV file found in dataset folder.")

df = pd.read_csv(csv_file)
print("Dataset loaded successfully.\n")

# -------------------------------
# STEP 4: Data inspection
# -------------------------------

print("First 5 rows of dataset:")
print(df.head(), "\n")

print("Dataset info:")
print(df.info(), "\n")

# Remove ID column if present
if 'Id' in df.columns or 'id' in df.columns:
    df.drop(columns=['Id'], inplace=True, errors='ignore')

# -------------------------------
# STEP 5: Feature & target split
# -------------------------------

X = df.drop('Species', axis=1)
y = df['Species']

# -------------------------------
# STEP 6: Train-test split
# -------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# -------------------------------
# STEP 7: Train ML model
# -------------------------------

model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)

# -------------------------------
# STEP 8: Predictions & Evaluation
# -------------------------------

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:", accuracy, "\n")

print("Classification Report:")
print(classification_report(y_test, y_pred))

# -------------------------------
# STEP 9: Confusion Matrix
# -------------------------------

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6, 4))
sns.heatmap(
    cm,
    annot=True,
    cmap="Blues",
    xticklabels=model.classes_,
    yticklabels=model.classes_
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix - Iris Flower Classification")
plt.tight_layout()
plt.show()